const PRODUCTS = [
  {
    id: "p1",
    name: "Samsung TV 4K",
    category: "Electronics",
    price: 499.0,
    icon: "📺",
    description: "Crystal-clear 4K UHD picture with vibrant color and smart TV features.",
    inStock: true,
  },
  {
    id: "p2",
    name: "T-Shirt",
    category: "Clothing",
    price: 25.0,
    icon: "👕",
    description: "Soft, breathable everyday tee. Easy fit for casual wear.",
    inStock: true,
  },
  {
    id: "p3",
    name: "Catcher in the Rye",
    category: "Books",
    price: 45.0,
    icon: "📘",
    description: "A classic novel following Holden Caulfield's journey and reflections.",
    inStock: false,
  },
  {
    id: "p4",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 120.0,
    icon: "🎧",
    description: "Comfortable over-ear wireless headphones with clear sound and deep bass.",
    inStock: true,
  },
  {
    id: "p5",
    name: "Modern Sofa",
    category: "Furniture",
    price: 850.0,
    icon: "🛋️",
    description: "Modern, minimalist sofa with supportive cushions and durable fabric.",
    inStock: true,
  },
  {
    id: "p6",
    name: "Wireless Mouse",
    category: "Electronics",
    price: 29.0,
    icon: "🖱️",
    description: "Compact wireless mouse with smooth tracking and comfortable grip.",
    inStock: true,
  },
  {
    id: "p7",
    name: "Wooden Table",
    category: "Furniture",
    price: 199.0,
    icon: "🪵",
    description: "Sturdy wooden table suitable for dining or workspace setup.",
    inStock: true,
  },
  {
    id: "p8",
    name: "Office Chair",
    category: "Furniture",
    price: 149.0,
    icon: "🪑",
    description: "Ergonomic office chair with adjustable height and lumbar support.",
    inStock: true,
  },
  {
    id: "p9",
    name: "Desk Lamp",
    category: "Electronics",
    price: 35.0,
    icon: "💡",
    description: "LED desk lamp with adjustable brightness for reading and work.",
    inStock: true,
  },
  {
    id: "p10",
    name: "Backpack",
    category: "Clothing",
    price: 48.0,
    icon: "🎒",
    description: "Lightweight backpack with multiple compartments for daily carry.",
    inStock: true,
  },
  {
    id: "p11",
    name: "Water Bottle",
    category: "Clothing",
    price: 18.0,
    icon: "🧴",
    description: "Reusable insulated bottle that keeps drinks cold or hot for hours.",
    inStock: true,
  },
  {
    id: "p12",
    name: "Notebook Journal",
    category: "Books",
    price: 12.0,
    icon: "📓",
    description: "Hardcover lined journal for notes, ideas, and daily planning.",
    inStock: true,
  },
];
